config/routes.rb
Rails.application.routes.draw do
  root 'cars#index'

  resources :cars
end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :find_car
  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.save
    redirect_to cars_path,
      notice: "#{@car.year} #{@car.make} #{@car.model} created"
  end

  def edit
    find_car
  end

  def find_car
    @car = Car.find(params[:id])
  end

  def update
    find_car
    @car.update(car_params)
    params.require(:car).permit(:make, :year, :model, :price)
  end

  private
  def car_params
    params.require(:car).permit(:make, :year, :model, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_from.html.erb
<%= form_for(@car) do |form| %>
    <p>
      <%= form.label :make %>
      <%= form.text_field :make %>
    </p>
    <p>
      <%= form.label :model %>
      <%= form.text_field :model %>
    </p>
    <p>
      <%= form.label :year %>
      <%= form.text_field :year %>
    </p>
    <p>
      <%= form.label :price %>
      <%= form.text_field :price %>
    </p>

    <%= form.submit %>
<% end %>

app/views/cars/edit.html.erb
<h2>Edit Car</h2>

<%= render 'from' %>

app/views/cars/index.html.erb
<p><%= notice %>

<%= link_to 'New Car', new_car_path %>

<table>
  <tr>
    <th>Make</th>
    <th>Model</th>
    <th>Year</th>
    <th>Price</th>
  </tr>

  <% @cars.each do |car| %>
    <tr>
      <td><%= car.make %></td>
      <td><%= car.model %></td>
      <td><%= car.year %></td>
      <td><%= number_to_currency(car.price) %></td>
      <td><%= link_to('Edit', edit_cars_path(car)) %></td>
    </tr>
  <% end %>
</table>

app/views/cars/new.html.erb
<h2>New Car</h2>

<%= render 'from' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DavinciMotors</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>

<%= yield %>

</body>
</html>